spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver

logging:
  level:
    org.springframework:
      jdbc: DEBUG
